"""initial migration

Revision ID: 9abb6d70bfc0
Revises: 
Create Date: 2021-01-17 12:05:13.406890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abb6d70bfc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_uid', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=512), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_organization_uid'), 'organizations', ['organization_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_organization_uid'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
